// @lane: local — exercises the tags lifecycle via decap-server file IO
//
// Closes task #51. Single end-to-end UI-driven flow that validates:
//   1. Adding a tag to a post via Decap's `tags` widget surfaces the
//      tag on the rendered post page, on /tags/, and on /tags/<slug>/.
//   2. Adding an entry in the Tags collection (with name + description)
//      surfaces the description on /tags/<slug>/.
//   3. Removing the tag from the post via UI cleans the post page.
//   4. Deleting the Tags-collection entry via UI cleans the description.
//
// Slimmed counter-proposal for PR #409 — single test with `test.step()`
// markers replaces the original 4-test serial chain. Same coverage; ~half
// the Jekyll-build cost (2 builds vs 4), one cold-start admin nav vs four,
// and full UI-driven cleanup including the test post itself (PR #409's
// fs.unlink-only afterAll was a back-door that AGENTS.md "No back doors
// in cleanup either" forbids). Failures still surface at the failing
// step in the Playwright report via test.step's name + caller frame.
//
// AGENTS.md compliance:
//   - "Never bypass the UI in a UI test": every state change is a
//     Decap UI click — tag attachment via the tags widget; tag entry
//     create via the Tags-collection editor; tag removal via the chip
//     × button; both tag entry deletion AND test post deletion via
//     the toolbar Delete button.
//   - "No back doors in cleanup either": post-test cleanup drives the
//     Decap UI delete on both the test post and the tag entry. The
//     afterAll safety-net only fires if a UI delete didn't unlink the
//     file (mirrors cms-publish-loop.spec.js's harness pattern after
//     commit 0f0ccb3) and logs a warning when it does.
const fs = require("node:fs");
const path = require("node:path");
const { execFileSync } = require("node:child_process");
const { test, expect } = require("./base");

const REPO_ROOT = path.join(__dirname, "..");
const POSTS_DIR = path.join(REPO_ROOT, "_posts");
const TAGS_DIR = path.join(REPO_ROOT, "_tags");

// Names reserved by this spec. Short enough to be readable in failure
// logs, prefixed `e2e-` so visual-regression and other transient-tag-
// aware filters skip them.
const TEST_POST_TITLE = "E2E Tags Lifecycle Test Post";
const TEST_POST_SLUG = "e2e-tags-lifecycle-test-post";
const TEST_POST_BASENAME = `2099-01-03-${TEST_POST_SLUG}.md`;
const TEST_TAG_NAME = "E2E Tags Test";
const TEST_TAG_SLUG = "e2e-tags-test";
const TEST_TAG_DESCRIPTION =
  "Auto-generated by cms-tags-lifecycle.spec.js — safe to delete.";

function jekyllBuild() {
  execFileSync("bundle", ["exec", "jekyll", "build", "--quiet"], {
    cwd: REPO_ROOT,
    stdio: "inherit",
  });
}

function findTestPostFile() {
  if (!fs.existsSync(POSTS_DIR)) return null;
  const entries = fs.readdirSync(POSTS_DIR);
  const found = entries.find(
    (n) => n === TEST_POST_BASENAME || n.endsWith(`-${TEST_POST_SLUG}.md`),
  );
  return found ? path.join(POSTS_DIR, found) : null;
}

function findTestTagFile() {
  if (!fs.existsSync(TAGS_DIR)) return null;
  const candidates = [
    path.join(TAGS_DIR, `${TEST_TAG_SLUG}.md`),
    path.join(
      TAGS_DIR,
      `${TEST_TAG_NAME.replace(/\s+/g, "-").toLowerCase()}.md`,
    ),
  ];
  return candidates.find((p) => fs.existsSync(p)) || null;
}

test.describe("CMS — tags lifecycle (local backend)", () => {
  // 6 min budget covers create-post + create-tag-entry + remove-tag +
  // delete-entry + delete-post + 2 Jekyll builds + UI clicks.
  test.describe.configure({ mode: "serial", timeout: 360_000 });

  // Pre-test hygiene: clear stale fixtures from a prior crashed run so
  // the spec asserts a clean baseline. This is hygiene, not state setup
  // — the spec itself drives Decap UI to seed the post + tag entry.
  test.beforeAll(() => {
    for (const f of [findTestPostFile(), findTestTagFile()].filter(Boolean)) {
      console.warn(`[pre-test-hygiene] removing stale fixture: ${f}`);
      try {
        fs.unlinkSync(f);
      } catch (_) {
        /* best-effort */
      }
    }
  });

  test.afterAll(() => {
    // Safety-net only — UI-delete steps in the test body should have
    // unlinked these. If anything remains, log a warning so a regression
    // in the UI-delete path doesn't get silently papered over by this
    // cleanup. AGENTS.md "No back doors in cleanup either" — this
    // shouldn't be the routine path.
    for (const f of [findTestPostFile(), findTestTagFile()].filter(Boolean)) {
      console.warn(
        `[cleanup-safety-net] file still on disk after UI-delete steps: ${f}`,
      );
      try {
        fs.unlinkSync(f);
      } catch (_) {
        /* best-effort */
      }
    }
    try {
      jekyllBuild();
    } catch (_) {
      /* best-effort */
    }
  });

  test.beforeEach(({ page }, testInfo) => {
    test.skip(
      testInfo.project.name !== "chromium-desktop",
      "Single project — local-backend Jekyll round-trip is heavy enough already.",
    );
    // Persistent dialog handler — Decap uses native window.confirm()
    // for delete. Without this listener Playwright auto-dismisses
    // and Decap reads it as "user cancelled."
    page.on("dialog", (d) => d.accept());
    page.on("pageerror", (err) =>
      console.log(`[pageerror] ${err.name}: ${err.message}`),
    );
  });

  test("attach + describe + remove + delete via Decap UI", async ({ page }) => {
    // ── Phase 1: create the post with the tag attached ──────────
    await test.step("create post with tag via Decap UI", async () => {
      await page.goto("/admin/index-local.html");
      await expect(
        page.getByRole("link", { name: /^Posts$/i }),
      ).toBeVisible({
        // 90s — local admin's first nav cold-starts decap-server +
        // Jekyll. cms-page-crud / cms-smoke use 60s; PR #409 run
        // #25507815016 timed out at 60s twice (initial + retry), so
        // widen the cap.
        timeout: 90_000,
      });

      await page.goto("/admin/index-local.html#/collections/posts/new", {
        waitUntil: "domcontentloaded",
      });
      const titleField = page.getByRole("textbox", { name: /^Title$/i });
      await expect(titleField).toBeVisible({ timeout: 30_000 });
      await titleField.fill(TEST_POST_TITLE);

      // Tags widget — type + Enter to chip.
      const tagsField = page.getByRole("textbox", { name: /^Tags$/i });
      await expect(tagsField).toBeVisible({ timeout: 30_000 });
      await tagsField.fill(TEST_TAG_NAME);
      await tagsField.press("Enter");

      // Body — markdown widget. Last contenteditable textbox.
      const body = page
        .locator('[role="textbox"][contenteditable="true"]')
        .last();
      await body.click();
      await body.pressSequentially("Body for tags lifecycle test.");

      await page.getByRole("button", { name: /^Save$/i }).click();
      await expect(page.getByText(/Changes saved/i).first()).toBeVisible({
        timeout: 60_000,
      });

      const postFile = findTestPostFile();
      expect(
        postFile,
        "Decap should have written the test post to _posts/",
      ).not.toBeNull();
      expect(fs.readFileSync(postFile, "utf8")).toMatch(
        new RegExp(`tags:\\s*\\n(?:\\s*-\\s*[^\\n]*\\n)*\\s*-\\s*${TEST_TAG_NAME}`),
      );
    });

    // ── Phase 2: create the Tags-collection entry with description ──
    await test.step(
      "create Tags-collection entry with description via Decap UI",
      async () => {
        await page.goto("/admin/index-local.html#/collections/tags/new", {
          waitUntil: "domcontentloaded",
        });
        const nameField = page.getByRole("textbox", { name: /^Name$/i });
        await expect(nameField).toBeVisible({ timeout: 30_000 });
        await nameField.fill(TEST_TAG_NAME);

        const descField = page
          .locator('[role="textbox"][contenteditable="true"]')
          .last();
        await descField.click();
        await descField.pressSequentially(TEST_TAG_DESCRIPTION);

        await page.getByRole("button", { name: /^Save$/i }).click();
        await expect(page.getByText(/Changes saved/i).first()).toBeVisible({
          timeout: 60_000,
        });

        const tagFile = findTestTagFile();
        expect(
          tagFile,
          "Decap should have written the tag entry to _tags/",
        ).not.toBeNull();
        const tagYaml = fs.readFileSync(tagFile, "utf8");
        expect(tagYaml).toMatch(new RegExp(`name:\\s*['"]?${TEST_TAG_NAME}`));
        expect(tagYaml).toContain(TEST_TAG_DESCRIPTION);
      },
    );

    // Single Jekyll build covers Phases 1+2's render assertions.
    await test.step(
      "rebuild Jekyll and assert all rendered surfaces (post + index + archive + description)",
      async () => {
        jekyllBuild();

        const postRes = await page.request.get(`/blog/${TEST_POST_SLUG}/`);
        expect(postRes.status()).toBe(200);
        const postHtml = await postRes.text();
        expect(postHtml).toContain(TEST_TAG_NAME);
        expect(postHtml).toMatch(
          new RegExp(
            `href="[^"]*/tags/${TEST_TAG_SLUG}/?[^"]*"[^>]*>[^<]*${TEST_TAG_NAME}`,
          ),
        );

        const indexRes = await page.request.get(`/tags/`);
        expect(indexRes.status()).toBe(200);
        const indexHtml = await indexRes.text();
        expect(indexHtml).toContain(TEST_TAG_NAME);
        expect(indexHtml).toMatch(
          new RegExp(`href="[^"]*/tags/${TEST_TAG_SLUG}/?"`),
        );

        const archiveRes = await page.request.get(`/tags/${TEST_TAG_SLUG}/`);
        expect(archiveRes.status()).toBe(200);
        const archiveHtml = await archiveRes.text();
        expect(archiveHtml).toContain(TEST_POST_TITLE);
        expect(archiveHtml).toContain(TEST_TAG_DESCRIPTION);
      },
    );

    // ── Phase 3: remove the tag from the post via UI ────────────
    await test.step(
      "remove tag from post via Decap UI chip × button",
      async () => {
        const editorBaseName = TEST_POST_BASENAME.replace(/\.md$/, "");
        await page.goto(
          `/admin/index-local.html#/collections/posts/entries/${editorBaseName}`,
          { waitUntil: "domcontentloaded" },
        );
        await expect(
          page.getByRole("textbox", { name: /^Title$/i }),
        ).toBeVisible({ timeout: 30_000 });

        // Decap renders chips with aria-label "Remove <tag>".
        await page
          .getByRole("button", {
            name: new RegExp(`remove ${TEST_TAG_NAME}`, "i"),
          })
          .first()
          .click({ timeout: 30_000 });

        await page.getByRole("button", { name: /^Save$/i }).click();
        await expect(page.getByText(/Changes saved/i).first()).toBeVisible({
          timeout: 60_000,
        });

        const postFile = findTestPostFile();
        expect(
          postFile,
          "post file should still exist after tag removal",
        ).not.toBeNull();
        expect(fs.readFileSync(postFile, "utf8")).not.toMatch(
          new RegExp(`-\\s*${TEST_TAG_NAME}`),
        );
      },
    );

    // ── Phase 4: delete the Tags-collection entry via UI ────────
    await test.step(
      "delete Tags-collection entry via Decap UI Delete button",
      async () => {
        await page.goto(
          `/admin/index-local.html#/collections/tags/entries/${TEST_TAG_SLUG}`,
          { waitUntil: "domcontentloaded" },
        );
        await expect(
          page.getByRole("textbox", { name: /^Name$/i }),
        ).toBeVisible({ timeout: 30_000 });

        // Local backend = simple Decap mode (no editorial workflow).
        // Delete button exposed directly, no Status menu in between.
        // The persistent dialog handler from beforeEach accepts the
        // confirm() that fires on click.
        await page
          .getByRole("button", {
            name: /^delete (entry|published entry)$/i,
          })
          .first()
          .click({ timeout: 30_000 });

        await expect
          .poll(() => findTestTagFile() === null, {
            message:
              "Tags entry file should be removed from disk after UI delete",
            timeout: 30_000,
          })
          .toBe(true);
      },
    );

    // ── Phase 5: rebuild Jekyll, assert cleanup landed across surfaces ──
    await test.step(
      "rebuild Jekyll and assert cleanup of all surfaces",
      async () => {
        jekyllBuild();

        const postRes = await page.request.get(`/blog/${TEST_POST_SLUG}/`);
        expect(postRes.status()).toBe(200);
        expect(await postRes.text()).not.toMatch(
          new RegExp(`href="[^"]*/tags/${TEST_TAG_SLUG}/?"`),
        );

        // /tags/<slug>/ may still exist (the auto-generator emits it
        // from any post still tagged) or 404 (no posts tag it now).
        // Either is acceptable; the deleted Tags entry's description
        // must NOT render in either case.
        const archiveRes = await page.request.get(
          `/tags/${TEST_TAG_SLUG}/`,
          { failOnStatusCode: false },
        );
        if (archiveRes.status() === 200) {
          expect(await archiveRes.text()).not.toContain(TEST_TAG_DESCRIPTION);
        }
      },
    );

    // ── Phase 6: delete the test post via UI (cleanup, UI-driven) ──
    // AGENTS.md "No back doors in cleanup either" — drive the post
    // deletion via Decap UI rather than fs.unlink. The afterAll
    // safety-net catches the file if this step fails.
    await test.step("delete test post via Decap UI (cleanup)", async () => {
      const editorBaseName = TEST_POST_BASENAME.replace(/\.md$/, "");
      await page.goto(
        `/admin/index-local.html#/collections/posts/entries/${editorBaseName}`,
        { waitUntil: "domcontentloaded" },
      );
      await expect(
        page.getByRole("textbox", { name: /^Title$/i }),
      ).toBeVisible({ timeout: 30_000 });

      await page
        .getByRole("button", {
          name: /^delete (entry|published entry)$/i,
        })
        .first()
        .click({ timeout: 30_000 });

      await expect
        .poll(() => findTestPostFile() === null, {
          message: "Test post should be removed from disk after UI delete",
          timeout: 30_000,
        })
        .toBe(true);
    });
  });
});
