// @lane: local — exercises the tags lifecycle via decap-server file IO
//
// Closes task #51. UI-driven validation that:
//   1. Adding a tag to a post via Decap's `tags` widget surfaces the
//      tag on the rendered post page, on /tags/ (the index), and on
//      /tags/<slug>/ (the auto-generated archive).
//   2. Adding an entry in the Tags collection (with name + description)
//      surfaces the description on /tags/<slug>/.
//   3. Removing the tag from the post AND deleting the Tags entry
//      cleans up across all surfaces.
//
// Local-backend (decap-server + Jekyll's webServer) — same pattern as
// cms-smoke / cms-page-crud. Faster + isolated than driving prod admin
// for a multi-step lifecycle, and the underlying Decap UI behavior is
// the same code path on both backends (sans the GitHub commit step).
//
// Per AGENTS.md "never bypass the UI": tag creation, tag attachment,
// tag removal, tag deletion are all clicks in the Decap UI. Setup and
// cleanup remove fixture files via filesystem (decap-server's local
// backend writes there anyway — there's no GitHub round-trip to bypass).
const path = require("node:path");
const fs = require("node:fs");
const { execFileSync } = require("node:child_process");
const { test, expect } = require("./base");

const REPO_ROOT = path.join(__dirname, "..");
const TAGS_DIR = path.join(REPO_ROOT, "_tags");
const POSTS_DIR = path.join(REPO_ROOT, "_posts");
// Names reserved by this spec — short enough to be readable in
// failure logs, prefixed `e2e-` so visual-regression and other
// transient-tag-aware filters skip them.
const TEST_POST_TITLE = "E2E Tags Lifecycle Test Post";
const TEST_POST_SLUG = "e2e-tags-lifecycle-test-post";
const TEST_POST_BASENAME = "2099-01-03-e2e-tags-lifecycle-test-post.md";
const TEST_TAG_NAME = "E2E Tags Test";
const TEST_TAG_SLUG = "e2e-tags-test";
const TEST_TAG_DESCRIPTION = "Auto-generated by cms-tags-lifecycle.spec.js — safe to delete.";

function jekyllBuild() {
  execFileSync("bundle", ["exec", "jekyll", "build", "--quiet"], {
    cwd: REPO_ROOT,
    stdio: "inherit",
  });
}

function findTestPostFile() {
  if (!fs.existsSync(POSTS_DIR)) return null;
  const entries = fs.readdirSync(POSTS_DIR);
  const found = entries.find(
    (name) => name === TEST_POST_BASENAME || name.endsWith(`-${TEST_POST_SLUG}.md`),
  );
  return found ? path.join(POSTS_DIR, found) : null;
}

function findTestTagFile() {
  if (!fs.existsSync(TAGS_DIR)) return null;
  const candidates = [
    path.join(TAGS_DIR, `${TEST_TAG_SLUG}.md`),
    path.join(TAGS_DIR, `${TEST_TAG_NAME.replace(/\s+/g, "-").toLowerCase()}.md`),
  ];
  return candidates.find((p) => fs.existsSync(p)) || null;
}

function cleanupFiles() {
  const post = findTestPostFile();
  if (post) {
    try {
      fs.unlinkSync(post);
    } catch (_) {
      /* swallow */
    }
  }
  const tag = findTestTagFile();
  if (tag) {
    try {
      fs.unlinkSync(tag);
    } catch (_) {
      /* swallow */
    }
  }
}

test.describe("CMS — tags lifecycle (local backend)", () => {
  test.describe.configure({ mode: "serial", timeout: 240_000 });

  test.beforeAll(() => cleanupFiles());
  test.afterAll(() => {
    cleanupFiles();
    try {
      jekyllBuild();
    } catch (_) {
      /* best-effort */
    }
  });

  test.beforeEach(({ page }, testInfo) => {
    test.skip(
      testInfo.project.name !== "chromium-desktop",
      "Single project — local-backend Jekyll round-trip is heavy enough already.",
    );
    // Persistent dialog handler — Decap uses native window.confirm()
    // for delete. Without this listener Playwright auto-dismisses
    // and Decap reads it as "user cancelled."
    page.on("dialog", (d) => d.accept());
    page.on("pageerror", (err) =>
      console.log(`[pageerror] ${err.name}: ${err.message}`),
    );
  });

  test("attach a tag to a post — tag surfaces on post page, /tags/, and /tags/<slug>/", async ({
    page,
  }) => {
    // ── Create the post via Decap UI, fill body, attach the tag ─────
    await page.goto("/admin/index-local.html");
    await expect(page.getByRole("link", { name: /^Posts$/i })).toBeVisible({
      timeout: 60_000,
    });
    await page.goto("/admin/index-local.html#/collections/posts/new", {
      waitUntil: "domcontentloaded",
    });
    const titleField = page.getByRole("textbox", { name: /^Title$/i });
    await expect(titleField).toBeVisible({ timeout: 30_000 });
    await titleField.fill(TEST_POST_TITLE);

    // The tags field is a list widget — type tag name + Enter to add.
    // Decap exposes the input as `getByPlaceholder` or via the field
    // label; the placeholder reads "Add tags" in this version.
    const tagsField = page.getByRole("textbox", { name: /^Tags$/i });
    await expect(tagsField).toBeVisible({ timeout: 30_000 });
    await tagsField.fill(TEST_TAG_NAME);
    await tagsField.press("Enter");

    // Body — markdown widget. Mirror cms-publish-loop.spec.js: grab
    // the last contenteditable textbox.
    const body = page.locator('[role="textbox"][contenteditable="true"]').last();
    await body.click();
    await body.pressSequentially("Body for tags lifecycle test.");

    // Save (writes the post to _posts/ via decap-server).
    await page.getByRole("button", { name: /^Save$/i }).click();
    await expect(page.getByText(/Changes saved/i).first()).toBeVisible({
      timeout: 60_000,
    });

    // Confirm decap-server actually wrote the file with the tag in
    // its frontmatter.
    const postFile = findTestPostFile();
    expect(postFile, "Decap should have written the test post to _posts/").not.toBeNull();
    const postYaml = fs.readFileSync(postFile, "utf8");
    expect(postYaml, "post frontmatter should list the tag").toMatch(
      new RegExp(`tags:\\s*\\n(?:\\s*-\\s*[^\\n]*\\n)*\\s*-\\s*${TEST_TAG_NAME}`),
    );

    // ── Rebuild Jekyll, then verify the rendered surfaces ──────────
    jekyllBuild();

    // 1. The post page lists the tag
    const postRes = await page.request.get(`/blog/${TEST_POST_SLUG}/`);
    expect(postRes.status(), "post page should be 200 after Jekyll build").toBe(200);
    const postHtml = await postRes.text();
    expect(postHtml, "post page should mention the tag name").toContain(TEST_TAG_NAME);
    // The post page links to the tag's archive page — pinned by URL.
    expect(postHtml).toMatch(
      new RegExp(`href="[^"]*/tags/${TEST_TAG_SLUG}/?[^"]*"[^>]*>[^<]*${TEST_TAG_NAME}`),
    );

    // 2. /tags/ index lists the tag
    const tagsIndexRes = await page.request.get(`/tags/`);
    expect(tagsIndexRes.status()).toBe(200);
    const tagsIndexHtml = await tagsIndexRes.text();
    expect(tagsIndexHtml, "/tags/ should list the new tag").toContain(TEST_TAG_NAME);
    expect(tagsIndexHtml).toMatch(
      new RegExp(`href="[^"]*/tags/${TEST_TAG_SLUG}/?"`),
    );

    // 3. /tags/<slug>/ archive lists the post
    const archiveRes = await page.request.get(`/tags/${TEST_TAG_SLUG}/`);
    expect(archiveRes.status()).toBe(200);
    const archiveHtml = await archiveRes.text();
    expect(
      archiveHtml,
      "/tags/<slug>/ should list the post that has this tag",
    ).toContain(TEST_POST_TITLE);
  });

  test("add a Tags-collection entry — description surfaces on /tags/<slug>/", async ({
    page,
  }) => {
    // Create a Tags-collection entry for the tag we attached above —
    // gives it a description that the archive page should render.
    await page.goto("/admin/index-local.html#/collections/tags/new", {
      waitUntil: "domcontentloaded",
    });
    const nameField = page.getByRole("textbox", { name: /^Name$/i });
    await expect(nameField).toBeVisible({ timeout: 30_000 });
    await nameField.fill(TEST_TAG_NAME);

    const descField = page.locator('[role="textbox"][contenteditable="true"]').last();
    await descField.click();
    await descField.pressSequentially(TEST_TAG_DESCRIPTION);

    await page.getByRole("button", { name: /^Save$/i }).click();
    await expect(page.getByText(/Changes saved/i).first()).toBeVisible({
      timeout: 60_000,
    });

    // Confirm the tag entry was written to disk.
    const tagFile = findTestTagFile();
    expect(tagFile, "Decap should have written the tag entry to _tags/").not.toBeNull();
    const tagYaml = fs.readFileSync(tagFile, "utf8");
    expect(tagYaml).toMatch(new RegExp(`name:\\s*['"]?${TEST_TAG_NAME}`));
    expect(tagYaml).toContain(TEST_TAG_DESCRIPTION);

    jekyllBuild();

    // The description should now show on /tags/<slug>/.
    const archiveRes = await page.request.get(`/tags/${TEST_TAG_SLUG}/`);
    expect(archiveRes.status()).toBe(200);
    const archiveHtml = await archiveRes.text();
    expect(
      archiveHtml,
      "/tags/<slug>/ should render the description from the Tags entry",
    ).toContain(TEST_TAG_DESCRIPTION);
  });

  test("remove tag from post — post page no longer mentions the tag", async ({
    page,
  }) => {
    // Open the post in the editor and remove the tag. The list widget
    // renders each tag as a chip with a delete (×) affordance —
    // click it, then save.
    await page.goto(
      `/admin/index-local.html#/collections/posts/entries/${TEST_POST_BASENAME.replace(/\.md$/, "")}`,
      { waitUntil: "domcontentloaded" },
    );
    await expect(page.getByRole("textbox", { name: /^Title$/i })).toBeVisible({
      timeout: 30_000,
    });

    // Remove the tag chip — Decap renders chips with an aria-label
    // like "Remove <tag>" in the list widget.
    const removeChip = page.getByRole("button", {
      name: new RegExp(`remove ${TEST_TAG_NAME}`, "i"),
    });
    await removeChip.first().click({ timeout: 30_000 });

    await page.getByRole("button", { name: /^Save$/i }).click();
    await expect(page.getByText(/Changes saved/i).first()).toBeVisible({
      timeout: 60_000,
    });

    const postFile = findTestPostFile();
    expect(postFile, "post file should still exist after tag removal").not.toBeNull();
    const postYaml = fs.readFileSync(postFile, "utf8");
    expect(
      postYaml,
      "post frontmatter should no longer list the tag",
    ).not.toMatch(new RegExp(`-\\s*${TEST_TAG_NAME}`));

    jekyllBuild();

    const postRes = await page.request.get(`/blog/${TEST_POST_SLUG}/`);
    expect(postRes.status()).toBe(200);
    const postHtml = await postRes.text();
    // The post page should no longer link to the tag's archive.
    expect(postHtml).not.toMatch(
      new RegExp(`href="[^"]*/tags/${TEST_TAG_SLUG}/?"`),
    );
  });

  test("delete the Tags-collection entry — description gone from /tags/<slug>/", async ({
    page,
  }) => {
    // Open the tag entry and delete it via the toolbar.
    await page.goto(
      `/admin/index-local.html#/collections/tags/entries/${TEST_TAG_SLUG}`,
      { waitUntil: "domcontentloaded" },
    );
    await expect(page.getByRole("textbox", { name: /^Name$/i })).toBeVisible({
      timeout: 30_000,
    });

    // Local backend: simple Decap mode (no editorial workflow), so
    // the Delete button is exposed directly with no Status menu in
    // between. Persistent dialog handler from beforeEach accepts the
    // confirm() that fires after the click.
    const deleteBtn = page.getByRole("button", {
      name: /^delete (entry|published entry)$/i,
    });
    await deleteBtn.first().click({ timeout: 30_000 });

    // After delete, decap-server unlinks the file.
    await expect.poll(() => findTestTagFile() === null, {
      message: "Tags entry file should be removed from disk after delete",
      timeout: 30_000,
    }).toBe(true);

    jekyllBuild();

    // /tags/<slug>/ may still exist (auto_tag_pages plugin generates
    // it from the post's frontmatter), but the description from the
    // Tags-collection entry should be gone.
    // Note: the post's tag was already removed in the prior test, so
    // /tags/<slug>/ may 404 entirely. Either is acceptable — the
    // assertion is "the Tags-entry's description doesn't render."
    const archiveRes = await page.request.get(`/tags/${TEST_TAG_SLUG}/`, {
      failOnStatusCode: false,
    });
    if (archiveRes.status() === 200) {
      const archiveHtml = await archiveRes.text();
      expect(
        archiveHtml,
        "deleted Tags entry's description should NOT render on /tags/<slug>/",
      ).not.toContain(TEST_TAG_DESCRIPTION);
    }
    // Status === 404 is also a valid outcome (post no longer tagged).
  });
});
