// @lane: local — exercises the locally-served Atom/RSS feeds + per-post share row
const { test, expect } = require("./base");

// Acceptance for the RSS/Atom feeds + per-post share row.
//
// The Atom feed for *all posts* is generated by jekyll-feed; the per-tag
// feeds are emitted by `_plugins/tag_feeds.rb` via `_layouts/atom_feed.xml`.
// Both flavors must share the same shape so any reader that subscribes
// to one parses the other.
//
// The share row lives on every post page; it is intentionally subtle —
// these tests verify presence and intent URLs, not pixels.

const ATOM_NS = 'xmlns="http://www.w3.org/2005/Atom"';
// allowed: literal slug used for known fixture (_posts/2026-04-25-replacement-test-post-1.md)
const POST_URL = "/blog/replacement-test-post-1/";
const POST_TITLE = "Replacement test post 1";
const TAG_SLUGS = ["best-practices", "python", "rag", "langchain"];

async function fetchText(page, url) {
  const response = await page.request.get(url);
  expect(response.status(), `${url} should respond 200`).toBe(200);
  return { response, body: await response.text() };
}

test.describe("Atom feeds", () => {
  test("/feed.xml exists, is Atom, and contains the right metadata", async ({
    page,
  }) => {
    const { response, body } = await fetchText(page, "/feed.xml");
    const ct = (response.headers()["content-type"] || "").toLowerCase();
    expect(ct).toMatch(/xml/);
    expect(body).toContain(ATOM_NS);
    expect(body).toMatch(/<feed\b/);
    expect(body).toMatch(
      /<link[^>]+(rel="self"[^>]+href="[^"]*feed\.xml|href="[^"]*feed\.xml"[^>]+rel="self")/,
    );
    expect(body).toMatch(/<title[^>]*>.*Adam Daniel.*<\/title>/);
  });

  for (const slug of TAG_SLUGS) {
    test(`/tags/${slug}/feed.xml exists and is a valid Atom feed`, async ({
      page,
    }) => {
      const { body } = await fetchText(page, `/tags/${slug}/feed.xml`);
      expect(body).toContain(ATOM_NS);
      expect(body).toMatch(/<feed\b/);
      expect(body).toMatch(
        new RegExp(
          `<link[^>]+href="[^"]*/tags/${slug}/feed\\.xml"[^>]+rel="self"`,
        ),
      );
      // Subtitle scopes the feed to the tag.
      expect(body).toMatch(/Posts tagged/);
    });
  }
});

test.describe("Feed-link icons surface the feeds in the UI", () => {
  test('homepage "Latest Posts" header links to /feed.xml', async ({
    page,
  }) => {
    await page.goto("/");
    const link = page.locator('.feed-link[href$="/feed.xml"]').first();
    await expect(link).toBeVisible();
    await expect(link).toHaveAttribute("aria-label", /Atom feed/i);
    // Icon is rendered, not a text label.
    await expect(link.locator("svg")).toBeVisible();
  });

  test("/blog/ header links to /feed.xml", async ({ page }) => {
    await page.goto("/blog/");
    const link = page.locator(".page-header .feed-link").first();
    await expect(link).toBeVisible();
    await expect(link).toHaveAttribute("href", /\/feed\.xml$/);
  });

  test("/tags/<slug>/ header links to its per-tag feed and advertises it in <head>", async ({
    page,
  }) => {
    const slug = "python";
    await page.goto(`/tags/${slug}/`);

    const link = page.locator(".page-header .feed-link").first();
    await expect(link).toBeVisible();
    await expect(link).toHaveAttribute(
      "href",
      new RegExp(`/tags/${slug}/feed\\.xml$`),
    );

    // Browser-discoverable feed in <head>.
    const alt = page.locator(
      `head link[rel="alternate"][type="application/atom+xml"][href$="/tags/${slug}/feed.xml"]`,
    );
    await expect(alt).toHaveCount(1);
  });
});

test.describe("Feed-link icon survives CSS load failure (webkit)", () => {
  // SVG without CSS reverts to its default replaced-element size — Firefox
  // and WebKit pick 300×150 if no width/height attributes survive on the
  // element. Without `assets/css/main.css`, the RSS icon shouldn't blow
  // up to that default. We exercise this on webkit projects because it's
  // the engine that surfaced the regression originally.
  test("RSS icon stays icon-sized when main.css fails to load", async ({
    page,
    browserName,
  }) => {
    test.skip(browserName !== "webkit", "webkit-only regression case");

    // Abort every main.css request so the icon renders unstyled.
    await page.route("**/main.css*", (route) => route.abort());

    await page.goto("/");
    const link = page.locator('.feed-link[href$="/feed.xml"]').first();
    const svg = link.locator("svg");
    await svg.waitFor({ state: "attached" });
    const box = await svg.boundingBox();
    expect(box, "svg must have a bounding box").not.toBeNull();
    // 16px is the conventional inline-icon size; allow up to that. A bare
    // SVG without width/height styling explodes to 300×150 — way over.
    expect(box.width).toBeLessThanOrEqual(16);
  });
});

test.describe("Share row on a post", () => {
  test("renders an understated share row at the bottom of the post", async ({
    page,
  }) => {
    await page.goto(POST_URL);

    const row = page.locator(".share-row");
    await expect(row).toBeVisible();
    await expect(row).toHaveAttribute("aria-label", /share/i);

    // Five icon links.
    const links = row.locator(".share-link");
    await expect(links).toHaveCount(5);

    // No visible text labels other than the small "Share" tag.
    await expect(row.locator(".share-row-label")).toHaveText(/share/i);
  });

  test("LinkedIn / X / Bluesky intents carry the post URL and title", async ({
    page,
  }) => {
    await page.goto(POST_URL);

    const row = page.locator(".share-row");
    const linkedin = row.locator('a[href*="linkedin.com/sharing"]');
    const x = row.locator('a[href*="twitter.com/intent/tweet"]');
    const bluesky = row.locator('a[href*="bsky.app/intent/compose"]');

    await expect(linkedin).toHaveCount(1);
    await expect(x).toHaveCount(1);
    await expect(bluesky).toHaveCount(1);

    const slug = "replacement-test-post-1";
    // url_encode in Liquid uses form-encoding (spaces → +), not %20 — match either.
    const titleHasWords = (s) =>
      /Replacement(\+|%20)test(\+|%20)post(\+|%20)1/.test(s);

    expect(await linkedin.getAttribute("href")).toContain(slug);
    const xHref = await x.getAttribute("href");
    expect(titleHasWords(xHref)).toBe(true);
    expect(xHref).toContain(slug);
    const bskyHref = await bluesky.getAttribute("href");
    expect(titleHasWords(bskyHref)).toBe(true);
    expect(bskyHref).toContain(slug);
  });

  test("Mastodon and Copy buttons are buttons (not links) and carry data attrs", async ({
    page,
  }) => {
    await page.goto(POST_URL);

    const masto = page.locator(".share-mastodon");
    const copy = page.locator(".share-copy");

    await expect(masto).toBeVisible();
    await expect(copy).toBeVisible();
    expect(await masto.evaluate((el) => el.tagName)).toBe("BUTTON");
    expect(await copy.evaluate((el) => el.tagName)).toBe("BUTTON");

    expect(await copy.getAttribute("data-share-copy-url")).toMatch(
      /\/blog\/replacement-test-post-1\/?$/,
    );
    expect(await masto.getAttribute("data-share-mastodon-url")).toMatch(
      /\/blog\/replacement-test-post-1\/?$/,
    );
  });

  test("Copy button writes the post URL to the clipboard", async ({
    page,
    browserName,
    context,
  }, testInfo) => {
    test.skip(
      browserName !== "chromium",
      "clipboard permission API is only reliably grantable on chromium",
    );
    test.skip(
      testInfo.project.use.forcedColors === "active",
      "skipping under forced-colors — not relevant to the JS behavior",
    );

    await context.grantPermissions(["clipboard-read", "clipboard-write"]);

    await page.goto(POST_URL);
    const copy = page.locator(".share-copy");
    await copy.click();

    await expect(copy).toHaveClass(/share-copied/);

    const clipboardText = await page.evaluate(() =>
      navigator.clipboard.readText(),
    );
    expect(clipboardText).toMatch(/\/blog\/replacement-test-post-1\/?$/);
  });
});
